name: Build Directory Structure

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'
        
    - name: Install dependencies
      run: npm install
        
    - name: Build directory structure
      run: npm run build
        
    - name: Commit changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add directory-list.json directory-flat.json
        git commit -m "Update directory structure" || echo "No changes to commit"
        git push || echo "No changes to push"
